### ISSUE TITLE
The method to test scalability

### ISSUE THREAD

**Issue by hengyuekang** [Thesys-lab/Segcache#11]
Hello!

I'm trying to test the scalability of Segcache and have some questions.

1. I used [genConf.sh](https://github.com/Thesys-lab/Segcache/blob/NSDI21/genConf.sh) in the repository. In genConf.sh, `heap_mem` increase with `n_thread` but you said "we used same cache size, but both make sense, it depends on your scenario" in https://github.com/Thesys-lab/Segcache/issues/4#issuecomment-1173285295. I'm confused about which I should follow. And using the same size, will there be more evictions leading to lower throughput(every thread runs the whole trace)?

2. If every thread runs the whole trace individually, will there be less inter-thread contention because they won't concurrently request(read/write) the same object?

**Comment by 1a1a11a** [comment]
Thank you for your interest! 
1. Sorry I was not clear. It has been some time since I ran the experiment. If I remember correctly, we used the same cache size, but we split the trace into sub-traces using a round-robin approach. Say if you use 16 threads, then the first request goes to `trace.1`, and the second request goes to `trace.2`, etc. 
2. If each thread runs the full trace, then you can map the object id to a different space in each thread, e.g., hash(concat(obj_id, thread_id)),  to reduce inter-thread contention. 

I hope this helps. :)
